# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fpga.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(857, 796)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.widget_4 = QtWidgets.QWidget(Form)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.widget_4)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout_2.addWidget(self.plainTextEdit)
        self.saveButton = QtWidgets.QPushButton(self.widget_4)
        self.saveButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.saveButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.saveButton.setObjectName("saveButton")
        self.verticalLayout_2.addWidget(self.saveButton, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addWidget(self.widget_4)
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 40))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.uploadCode = QtWidgets.QPushButton(self.widget_2)
        self.uploadCode.setObjectName("uploadCode")
        self.horizontalLayout_2.addWidget(self.uploadCode)
        self.codePath = QtWidgets.QLineEdit(self.widget_2)
        self.codePath.setObjectName("codePath")
        self.horizontalLayout_2.addWidget(self.codePath)
        self.verticalLayout.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(Form)
        self.widget_3.setMinimumSize(QtCore.QSize(0, 40))
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.uploadCon = QtWidgets.QPushButton(self.widget_3)
        self.uploadCon.setObjectName("uploadCon")
        self.horizontalLayout_3.addWidget(self.uploadCon)
        self.conPath = QtWidgets.QLineEdit(self.widget_3)
        self.conPath.setObjectName("conPath")
        self.horizontalLayout_3.addWidget(self.conPath)
        self.verticalLayout.addWidget(self.widget_3)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setMinimumSize(QtCore.QSize(0, 40))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.compileButton = QtWidgets.QPushButton(self.widget)
        self.compileButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.compileButton.setObjectName("compileButton")
        self.horizontalLayout.addWidget(self.compileButton, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Write you code"))
        self.saveButton.setText(_translate("Form", "save"))
        self.uploadCode.setText(_translate("Form", "Upload Code:"))
        self.uploadCon.setText(_translate("Form", "Upload Cons:"))
        self.compileButton.setText(_translate("Form", "Compile and Prog"))
