# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pcmd.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\npcmd.proto\"\x19\n\tCnnResult\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\x15\n\x06\x43nnCmd\x12\x0b\n\x03img\x18\x01 \x01(\x0c\" \n\x10\x44ownloadsBitsCmd\x12\x0c\n\x04\x62its\x18\x01 \x01(\x0c\"\x19\n\tRetStatus\x12\x0c\n\x04isOK\x18\x01 \x01(\x08\x32[\n\x0bPynqService\x12\x1d\n\x06runCnn\x12\x07.CnnCmd\x1a\n.CnnResult\x12-\n\x0c\x64ownloadBits\x12\x11.DownloadsBitsCmd\x1a\n.RetStatusb\x06proto3')



_CNNRESULT = DESCRIPTOR.message_types_by_name['CnnResult']
_CNNCMD = DESCRIPTOR.message_types_by_name['CnnCmd']
_DOWNLOADSBITSCMD = DESCRIPTOR.message_types_by_name['DownloadsBitsCmd']
_RETSTATUS = DESCRIPTOR.message_types_by_name['RetStatus']
CnnResult = _reflection.GeneratedProtocolMessageType('CnnResult', (_message.Message,), {
  'DESCRIPTOR' : _CNNRESULT,
  '__module__' : 'pcmd_pb2'
  # @@protoc_insertion_point(class_scope:CnnResult)
  })
_sym_db.RegisterMessage(CnnResult)

CnnCmd = _reflection.GeneratedProtocolMessageType('CnnCmd', (_message.Message,), {
  'DESCRIPTOR' : _CNNCMD,
  '__module__' : 'pcmd_pb2'
  # @@protoc_insertion_point(class_scope:CnnCmd)
  })
_sym_db.RegisterMessage(CnnCmd)

DownloadsBitsCmd = _reflection.GeneratedProtocolMessageType('DownloadsBitsCmd', (_message.Message,), {
  'DESCRIPTOR' : _DOWNLOADSBITSCMD,
  '__module__' : 'pcmd_pb2'
  # @@protoc_insertion_point(class_scope:DownloadsBitsCmd)
  })
_sym_db.RegisterMessage(DownloadsBitsCmd)

RetStatus = _reflection.GeneratedProtocolMessageType('RetStatus', (_message.Message,), {
  'DESCRIPTOR' : _RETSTATUS,
  '__module__' : 'pcmd_pb2'
  # @@protoc_insertion_point(class_scope:RetStatus)
  })
_sym_db.RegisterMessage(RetStatus)

_PYNQSERVICE = DESCRIPTOR.services_by_name['PynqService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CNNRESULT._serialized_start=14
  _CNNRESULT._serialized_end=39
  _CNNCMD._serialized_start=41
  _CNNCMD._serialized_end=62
  _DOWNLOADSBITSCMD._serialized_start=64
  _DOWNLOADSBITSCMD._serialized_end=96
  _RETSTATUS._serialized_start=98
  _RETSTATUS._serialized_end=123
  _PYNQSERVICE._serialized_start=125
  _PYNQSERVICE._serialized_end=216
# @@protoc_insertion_point(module_scope)
