# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import pcmd_pb2 as pcmd__pb2


class PynqServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.runCnn = channel.unary_unary(
                '/PynqService/runCnn',
                request_serializer=pcmd__pb2.CnnCmd.SerializeToString,
                response_deserializer=pcmd__pb2.CnnResult.FromString,
                )
        self.downloadBits = channel.unary_unary(
                '/PynqService/downloadBits',
                request_serializer=pcmd__pb2.DownloadsBitsCmd.SerializeToString,
                response_deserializer=pcmd__pb2.RetStatus.FromString,
                )


class PynqServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def runCnn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def downloadBits(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PynqServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'runCnn': grpc.unary_unary_rpc_method_handler(
                    servicer.runCnn,
                    request_deserializer=pcmd__pb2.CnnCmd.FromString,
                    response_serializer=pcmd__pb2.CnnResult.SerializeToString,
            ),
            'downloadBits': grpc.unary_unary_rpc_method_handler(
                    servicer.downloadBits,
                    request_deserializer=pcmd__pb2.DownloadsBitsCmd.FromString,
                    response_serializer=pcmd__pb2.RetStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'PynqService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PynqService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def runCnn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PynqService/runCnn',
            pcmd__pb2.CnnCmd.SerializeToString,
            pcmd__pb2.CnnResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def downloadBits(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PynqService/downloadBits',
            pcmd__pb2.DownloadsBitsCmd.SerializeToString,
            pcmd__pb2.RetStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
